'use client';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
export default function Page() { return <div className="mx-auto flex max-w-5xl flex-col gap-6"><div><h1 className="text-3xl font-bold">Pengaturan</h1><p className="mt-1 text-muted-foreground">Kelola profil bengkel dan preferensi sistem.</p></div><Tabs defaultValue="business"><TabsList><TabsTrigger value="business">Informasi Bisnis</TabsTrigger><TabsTrigger value="profile">Profil Bengkel</TabsTrigger><TabsTrigger value="system">Preferensi Sistem</TabsTrigger></TabsList><TabsContent value="business" className="mt-5"><Card><CardHeader><CardTitle>Informasi Bisnis</CardTitle><CardDescription>Informasi ini ditampilkan pada struk dan laporan.</CardDescription></CardHeader><CardContent><FieldGroup><Field><FieldLabel>Nama Bengkel</FieldLabel><Input defaultValue="DIAN MOTOR"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field><FieldLabel>Nomor Telepon</FieldLabel><Input defaultValue="021-555-0182"/></Field><Field><FieldLabel>Jam Operasional</FieldLabel><Input defaultValue="Senin–Sabtu, 08.00–18.00"/></Field></div><Field><FieldLabel>Alamat</FieldLabel><Textarea defaultValue="Jl. Raya Otomotif No. 24, Jakarta"/></Field><Button onClick={() => toast.success('Pengaturan berhasil disimpan.')}>Simpan Perubahan</Button></FieldGroup></CardContent></Card></TabsContent>{['profile', 'system'].map(v => <TabsContent key={v} value={v} className="mt-5"><Card><CardContent className="py-16 text-center text-muted-foreground">Pengaturan tersedia setelah Supabase dikonfigurasi.</CardContent></Card></TabsContent>)}</Tabs></div>; }
