import { ArrowDownToLine, ArrowUpFromLine, Boxes, PackageSearch, ReceiptText, TrendingUp } from 'lucide-react';
import Link from 'next/link';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { SalesChart } from '@/components/sales-chart';
import { StockBadge } from '@/components/stock-badge';
import { PageHeader } from '@/components/page-header';
import { products, rupiah, transactions } from '@/lib/demo-data';
const stats = [
    ['Penjualan Hari Ini', rupiah(3892000), '+12,5% dari kemarin', TrendingUp], ['Transaksi Hari Ini', '18', '+3 dari kemarin', ReceiptText], ['Total Produk', '248', '12 kategori', Boxes], ['Stok Menipis', '7', 'Perlu tindakan', PackageSearch], ['Barang Masuk', '32', 'Bulan ini', ArrowDownToLine], ['Barang Keluar', '118', 'Bulan ini', ArrowUpFromLine],
];
const today = new Date().toLocaleDateString('id-ID', { day: '2-digit', month: 'short', year: 'numeric' });
export default function DashboardPage() {
    const low = products.filter((p) => p.stock <= p.minimumStock);
    return <div className="flex flex-col gap-5"><PageHeader eyebrow="OPERATION OVERVIEW" title="Dashboard" description="Selamat datang kembali di sistem DIAN MOTOR"> <Button variant="outline">{today}</Button></PageHeader>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{stats.map(([label, value, note, Icon], i) => <div key={label} className={`metric-card ${i === 3 ? 'warning' : ''}`}><div className="flex items-start justify-between"><p className="text-sm text-muted-foreground">{label}</p><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5"/></span></div><strong className="mt-1 block text-2xl font-bold tracking-[-.03em]">{value}</strong><p className={`mt-1 text-xs ${i === 3 ? 'font-medium text-primary' : 'text-muted-foreground'}`}>{note}</p></div>)}</section>
    <section className="grid gap-4 xl:grid-cols-[1.65fr_1fr]"><Card className="rounded-[17px]"><CardHeader className="flex-row items-start justify-between"><div><CardTitle>Ringkasan Penjualan</CardTitle><CardDescription>Performa penjualan 7 hari terakhir</CardDescription></div><Badge variant="secondary">Minggu Ini</Badge></CardHeader><CardContent><SalesChart /></CardContent></Card><Card className="rounded-[17px]"><CardHeader><CardTitle>Perhatian Stok</CardTitle><CardDescription>Produk yang perlu segera ditindaklanjuti</CardDescription></CardHeader><CardContent className="flex flex-col gap-4">{low.map(p => <div key={p.id} className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-semibold">{p.name}</p><p className="text-xs text-muted-foreground">{p.code} · Tersisa {p.stock} {p.unit}</p></div><StockBadge stock={p.stock} minimum={p.minimumStock}/></div>)}<Button render={<Link href="/stok" />} variant="outline" className="w-full">Lihat Semua Stok</Button></CardContent></Card></section>
    <Card className="rounded-[17px]"><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Transaksi Terbaru</CardTitle><CardDescription>Aktivitas penjualan terkini</CardDescription></div><Button render={<Link href="/transaksi" />} variant="ghost">Lihat Semua</Button></CardHeader><CardContent><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>ID Transaksi</TableHead><TableHead>Tanggal</TableHead><TableHead>Pelanggan</TableHead><TableHead>Metode</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Total</TableHead></TableRow></TableHeader><TableBody>{transactions.map(t => <TableRow key={t.id}><TableCell className="font-mono text-xs">{t.id}</TableCell><TableCell>{t.date}</TableCell><TableCell>{t.customer}</TableCell><TableCell>{t.method}</TableCell><TableCell><Badge variant="secondary">{t.status}</Badge></TableCell><TableCell className="text-right font-semibold">{rupiah(t.total)}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>
  </div>;
}