'use client';
import { useState } from 'react';
import { Download, MoreHorizontal, Plus, Search } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field';
const datasets = {
    Produk: [['OLI-001', 'Oli Mesin MPX 1 0.8L', 'Oli', '24 Botol', 'Rp58.000'], ['REM-014', 'Kampas Rem Depan Vario', 'Sparepart', '4 Set', 'Rp68.000'], ['BUS-007', 'Busi NGK CPR9EA-9', 'Kelistrikan', '18 Pcs', 'Rp26.000']],
    Kategori: [['Oli', 'Pelumas mesin dan transmisi', '12 produk'], ['Sparepart', 'Suku cadang kendaraan', '86 produk'], ['Ban', 'Ban dalam dan luar', '28 produk'], ['Kelistrikan', 'Komponen kelistrikan', '34 produk']],
    Supplier: [['PT Sumber Motor', '0812-4455-6677', 'sales@sumbermotor.id', '42 produk'], ['CV Karya Otomotif', '0813-8877-2211', 'order@karyaoto.id', '26 produk']],
    Pelanggan: [['Budi Santoso', '0812-3456-7890', 'Jl. Melati No. 18', '12 transaksi'], ['Siti Aminah', '0821-8855-4422', 'Jl. Kenanga No. 7', '8 transaksi']],
    Servis: [['SRV-260827-012', 'Budi Santoso', 'B 4123 KLM', 'Ganti oli & tune up', 'Dikerjakan'], ['SRV-260827-011', 'Andi Pratama', 'B 9081 PQR', 'Perbaikan rem', 'Menunggu'], ['SRV-260826-010', 'Siti Aminah', 'F 2281 AA', 'Servis berkala', 'Selesai']],
    Transaksi: [['TRX-260827-018', '27 Agu 2026', 'Budi Santoso', 'Rp246.000', 'Selesai'], ['TRX-260827-017', '27 Agu 2026', 'Pelanggan Umum', 'Rp116.000', 'Selesai']],
    Pengguna: [['Admin Bengkel', 'admin@dianmotor.id', 'Admin', 'Aktif'], ['Rina Kasir', 'rina@dianmotor.id', 'Kasir', 'Aktif'], ['Dedi Mekanik', 'dedi@dianmotor.id', 'Mekanik', 'Aktif']],
};
const headers = { Produk: ['Kode', 'Nama Produk', 'Kategori', 'Stok', 'Harga Jual'], Kategori: ['Nama', 'Deskripsi', 'Jumlah'], Supplier: ['Nama Supplier', 'Nomor Telepon', 'Email', 'Produk'], Pelanggan: ['Nama', 'Nomor Telepon', 'Alamat', 'Riwayat'], Servis: ['Nomor Servis', 'Pelanggan', 'Kendaraan', 'Jenis Servis', 'Status'], Transaksi: ['ID Transaksi', 'Tanggal', 'Pelanggan', 'Total', 'Status'], Pengguna: ['Nama', 'Email', 'Peran', 'Status'] };
export function ManagementPage({ title, description, addLabel }) { const [open, setOpen] = useState(false); const rows = datasets[title] ?? []; return <div className="flex flex-col gap-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-bold">{title}</h1><p className="mt-1 text-muted-foreground">{description}</p></div>{addLabel && <Dialog open={open} onOpenChange={setOpen}><DialogTrigger render={<Button />}><Plus data-icon="inline-start"/>{addLabel}</DialogTrigger><DialogContent><DialogHeader><DialogTitle>{addLabel}</DialogTitle><DialogDescription>Lengkapi informasi berikut untuk menyimpan data.</DialogDescription></DialogHeader><FieldGroup><Field><FieldLabel>Nama</FieldLabel><Input placeholder="Masukkan nama..." required/></Field><Field><FieldLabel>Keterangan</FieldLabel><Input placeholder="Masukkan keterangan..."/></Field></FieldGroup><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Batal</Button><Button onClick={() => { toast.success('Data berhasil disimpan.'); setOpen(false); }}>Simpan</Button></DialogFooter></DialogContent></Dialog>}</div><Card><CardContent className="p-4"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:justify-between"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="pl-9" placeholder={`Cari ${title.toLowerCase()}...`}/></div>{title === 'Transaksi' && <Button variant="outline"><Download data-icon="inline-start"/>Unduh CSV</Button>}</div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b">{(headers[title] ?? []).map(h => <th key={h} className="px-3 py-3 font-medium text-muted-foreground">{h}</th>)}<th className="px-3 py-3 text-right">Aksi</th></tr></thead><tbody>{rows.map((r, i) => <tr key={i} className="border-b last:border-0">{r.map((c, j) => <td key={j} className="px-3 py-4">{j === r.length - 1 && (c === 'Selesai' || c === 'Aktif' || c === 'Menunggu' || c === 'Dikerjakan') ? <Badge variant={c === 'Menunggu' ? 'outline' : 'secondary'}>{c}</Badge> : c}</td>)}<td className="px-3 py-4 text-right"><Button variant="ghost" size="icon"><MoreHorizontal /><span className="sr-only">Aksi</span></Button></td></tr>)}</tbody></table></div>{!rows.length && <p className="py-16 text-center text-muted-foreground">Belum ada data {title.toLowerCase()}.</p>}</CardContent></Card></div>; }
