'use client';
import { useActionState } from 'react';
import { Eye, LockKeyhole, Mail, Wrench } from 'lucide-react';
import { loginAction } from './actions';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { Alert, AlertDescription } from '@/components/ui/alert';
export default function LoginPage() {
    const [state, action, pending] = useActionState(loginAction, { error: '' });
    return <main className="grid min-h-screen bg-background lg:grid-cols-[1.05fr_.95fr]">
    <section className="hidden bg-sidebar p-12 text-sidebar-foreground lg:flex lg:flex-col lg:justify-between"><div className="flex items-center gap-3"><span className="flex size-12 items-center justify-center rounded-lg bg-primary text-xl font-black text-primary-foreground">DM</span><div><p className="text-xl font-bold">DIAN MOTOR</p><p className="text-sm text-sidebar-foreground/60">Sistem Manajemen Bengkel</p></div></div><div className="max-w-xl"><Wrench className="mb-6 size-14 text-primary"/><h1 className="text-balance text-5xl font-extrabold leading-tight">Kerja bengkel lebih cepat, stok lebih akurat.</h1><p className="mt-5 max-w-lg text-lg leading-relaxed text-sidebar-foreground/60">Kelola penjualan, persediaan, dan pekerjaan servis dalam satu sistem yang praktis.</p></div><p className="text-sm text-sidebar-foreground/40">© 2026 DIAN MOTOR. Sistem operasional internal.</p></section>
    <section className="flex items-center justify-center p-5 md:p-10"><Card className="w-full max-w-md border-0 shadow-none sm:border sm:shadow-sm"><CardHeader className="gap-2"><div className="mb-3 flex items-center gap-3 lg:hidden"><span className="flex size-10 items-center justify-center rounded-lg bg-primary font-black text-primary-foreground">DM</span><strong>DIAN MOTOR</strong></div><CardTitle className="text-3xl">Selamat datang kembali</CardTitle><CardDescription>Masuk untuk melanjutkan ke sistem DIAN MOTOR.</CardDescription></CardHeader><CardContent><form action={action}><FieldGroup><Field><FieldLabel htmlFor="email">Email</FieldLabel><div className="relative"><Mail className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input id="email" name="email" type="email" className="pl-9" placeholder="admin@dianmotor.id" required autoComplete="email"/></div></Field><Field><div className="flex items-center justify-between"><FieldLabel htmlFor="password">Password</FieldLabel><a href="#" className="text-sm font-medium text-primary">Lupa password?</a></div><div className="relative"><LockKeyhole className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input id="password" name="password" type="password" className="px-9" required autoComplete="current-password"/><Eye className="absolute right-3 top-3 size-4 text-muted-foreground"/></div></Field><div className="flex items-center gap-2"><Checkbox id="remember" name="remember"/><label htmlFor="remember" className="text-sm">Ingat saya</label></div>{state.error && <Alert variant="destructive"><AlertDescription>{state.error}</AlertDescription></Alert>}<Button type="submit" size="lg" disabled={pending} className="w-full">{pending ? 'Memproses...' : 'Masuk'}</Button></FieldGroup></form><p className="mt-6 text-center text-xs leading-relaxed text-muted-foreground">Akses terbatas untuk staf DIAN MOTOR yang berwenang.</p></CardContent></Card></section>
  </main>;
}
