'use client';
import { useMemo, useState } from 'react';
import { MoreHorizontal, Search } from 'lucide-react';
import { products, rupiah, stockStatus } from '@/lib/demo-data';
import { StockBadge } from '@/components/stock-badge';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
export default function StockPage() {
    const [query, setQuery] = useState('');
    const [filter, setFilter] = useState('Semua');
    const data = useMemo(() => products.filter(p => (`${p.name} ${p.code}`).toLowerCase().includes(query.toLowerCase()) && (filter === 'Semua' || stockStatus(p.stock, p.minimumStock) === filter)), [query, filter]);
    return <div className="flex flex-col gap-6"><div><h1 className="text-3xl font-bold">Cek Stok</h1><p className="mt-1 text-muted-foreground">Pantau ketersediaan barang secara cepat dan akurat.</p></div><Card><CardContent className="flex flex-col gap-4 p-4"><div className="flex flex-col gap-3 md:flex-row md:justify-between"><div className="relative w-full md:max-w-md"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input value={query} onChange={e => setQuery(e.target.value)} className="pl-9" placeholder="Cari nama barang atau kode barang..."/></div><div className="flex gap-2 overflow-x-auto">{['Semua', 'Stok Aman', 'Stok Menipis', 'Stok Habis'].map(v => <Button key={v} onClick={() => setFilter(v)} variant={filter === v ? 'default' : 'outline'} size="sm">{v}</Button>)}</div></div><div className="hidden overflow-x-auto md:block"><Table><TableHeader><TableRow><TableHead>Kode Barang</TableHead><TableHead>Nama Barang</TableHead><TableHead>Kategori</TableHead><TableHead>Stok</TableHead><TableHead>Minimum</TableHead><TableHead>Harga Jual</TableHead><TableHead>Status</TableHead><TableHead>Aksi</TableHead></TableRow></TableHeader><TableBody>{data.map(p => <TableRow key={p.id}><TableCell className="font-mono text-xs">{p.code}</TableCell><TableCell className="font-semibold">{p.name}</TableCell><TableCell>{p.category}</TableCell><TableCell className="text-lg font-bold">{p.stock} <small className="font-normal text-muted-foreground">{p.unit}</small></TableCell><TableCell>{p.minimumStock}</TableCell><TableCell>{rupiah(p.sellingPrice)}</TableCell><TableCell><StockBadge stock={p.stock} minimum={p.minimumStock}/></TableCell><TableCell><Button variant="ghost" size="icon"><MoreHorizontal /><span className="sr-only">Aksi</span></Button></TableCell></TableRow>)}</TableBody></Table></div><div className="grid gap-3 md:hidden">{data.map(p => <article key={p.id} className="rounded-lg border p-4"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-mono text-muted-foreground">{p.code}</p><h2 className="mt-1 font-semibold">{p.name}</h2></div><StockBadge stock={p.stock} minimum={p.minimumStock}/></div><div className="mt-4 flex items-end justify-between"><div><p className="text-xs text-muted-foreground">Stok tersedia</p><p className="text-3xl font-bold">{p.stock} <span className="text-sm font-normal">{p.unit}</span></p></div><p className="text-sm font-semibold">{rupiah(p.sellingPrice)}</p></div></article>)}</div>{data.length === 0 && <p className="py-14 text-center text-muted-foreground">Belum ada data barang yang sesuai.</p>}</CardContent></Card></div>;
}
