'use client';
import { useMemo, useState } from 'react';
import { Boxes, MoreHorizontal, Search } from 'lucide-react';
import { products, rupiah, stockStatus } from '@/lib/demo-data';
import { StockBadge } from '@/components/stock-badge';
import { PageHeader } from '@/components/page-header';
import { Button } from '@/components/ui/button';
const filters = ['Semua', 'Stok Aman', 'Stok Menipis', 'Stok Habis'];
const counts = {
    'Stok Aman': products.filter(p => stockStatus(p.stock, p.minimumStock) === 'Stok Aman').length,
    'Stok Menipis': products.filter(p => stockStatus(p.stock, p.minimumStock) === 'Stok Menipis').length,
    'Stok Habis': products.filter(p => stockStatus(p.stock, p.minimumStock) === 'Stok Habis').length,
};
export default function StockPage() {
    const [query, setQuery] = useState('');
    const [filter, setFilter] = useState('Semua');
    const data = useMemo(() => products.filter(p => (`${p.name} ${p.code}`).toLowerCase().includes(query.toLowerCase()) && (filter === 'Semua' || stockStatus(p.stock, p.minimumStock) === filter)), [query, filter]);
    return <div className="flex flex-col gap-5"><PageHeader eyebrow="LIVE INVENTORY" title="Cek Stok" description="Pantau ketersediaan barang secara cepat dan akurat."> <Button variant="outline"><Boxes data-icon="inline-start"/>Sinkronkan</Button></PageHeader>
    <section className="grid gap-3 sm:grid-cols-3">{[['Total SKU', '248', 'sku tercatat'], ['Stok Menipis', String(counts['Stok Menipis'] + counts['Stok Habis']), 'perlu tindakan'], ['Nilai Persediaan', rupiah(64325000), 'estimasi harga beli']].map(([label, value, note], i) => <div key={label} className={`metric-card ${i === 1 ? 'warning' : ''}`}><p className="text-sm text-muted-foreground">{label}</p><strong className="mt-1 block text-2xl font-bold tracking-[-.03em]">{value}</strong><p className="mt-1 text-xs text-muted-foreground">{note}</p></div>)}</section>
    <div className="table-surface">
      <div className="flex flex-col gap-3 border-b border-border p-3.5 xl:flex-row xl:items-center xl:justify-between"><div className="input-with-icon min-w-0 flex-1"><Search className="size-4"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Cari nama barang atau kode barang..." className="h-10 min-w-0 w-full rounded-xl border border-border bg-transparent pl-10 pr-4 text-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-primary focus:ring-3 focus:ring-primary/10"/></div><div className="flex gap-1.5 overflow-x-auto">{filters.map(v => <button key={v} type="button" onClick={() => setFilter(v)} className={`flex h-9 shrink-0 items-center gap-1.5 rounded-lg px-3 text-xs font-semibold transition-colors ${filter === v ? 'bg-primary text-white' : 'border border-border bg-card text-muted-foreground hover:text-foreground'}`}>{v}{v !== 'Semua' && <span className="rounded-full bg-black/10 px-1.5 font-mono text-[10px] dark:bg-white/10">{counts[v]}</span>}</button>)}</div></div>
      <div className="hidden overflow-x-auto md:block"><table className="w-full"><thead><tr className="border-b border-border">{[['Kode Barang', 'mono'], ['Nama Barang', 'left'], ['Kategori', 'left'], ['Stok', 'left'], ['Minimum', 'left'], ['Harga Jual', 'right'], ['Status', 'left'], ['Aksi', 'right']].map(([h, align]) => <th key={h} className={`px-3.5 py-2.5 font-medium uppercase tracking-wide ${align === 'right' ? 'text-right' : 'text-left'}`}>{h}</th>)}</tr></thead><tbody>{data.map(p => <tr key={p.id} className="border-b border-border transition-colors last:border-0 hover:bg-muted/50"><td className="px-3.5 py-3 font-mono text-xs">{p.code}</td><td className="px-3.5 py-3 text-[13px] font-semibold">{p.name}</td><td className="px-3.5 py-3 text-[13px] text-muted-foreground">{p.category}</td><td className="px-3.5 py-3"><strong className="text-base">{p.stock}</strong> <small className="text-xs text-muted-foreground">{p.unit}</small></td><td className="px-3.5 py-3 text-[13px]">{p.minimumStock}</td><td className="px-3.5 py-3 text-right text-[13px] font-semibold">{rupiah(p.sellingPrice)}</td><td className="px-3.5 py-3"><StockBadge stock={p.stock} minimum={p.minimumStock}/></td><td className="px-3.5 py-3 text-right"><Button variant="ghost" size="icon-sm"><MoreHorizontal /><span className="sr-only">Aksi</span></Button></td></tr>)}</tbody></table></div>
      <div className="grid gap-3 p-3 md:hidden">{data.map(p => <article key={p.id} className="rounded-xl border border-border p-4"><div className="flex items-start justify-between gap-2"><div><p className="font-mono text-[10px] text-muted-foreground">{p.code}</p><h2 className="mt-1 text-sm font-semibold">{p.name}</h2></div><span className="part-cell"><span>{p.name.split(' ').slice(0, 2).map(w => w[0]).join('').toUpperCase()}</span></span></div><div className="mt-3 flex items-center justify-between"><strong>{p.stock} <small className="font-normal text-muted-foreground">{p.unit}</small></strong><StockBadge stock={p.stock} minimum={p.minimumStock}/></div><p className="mt-1 text-xs text-muted-foreground">{p.category} · {rupiah(p.sellingPrice)}</p></article>)}</div>
    </div>
  </div>;
}