'use client';
import { Download } from 'lucide-react';
import { SalesChart } from '@/components/sales-chart';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { PageHeader } from '@/components/page-header';
import { rupiah } from '@/lib/demo-data';
export default function Page() { return <div className="flex flex-col gap-5"><PageHeader eyebrow="ANALYTICS & REPORTING" title="Laporan" description="Analisis operasional dan kinerja DIAN MOTOR."> <Button><Download data-icon="inline-start"/>Unduh Laporan</Button></PageHeader>
    <Tabs defaultValue="sales" className="gap-4"><TabsList variant="line" className="h-auto w-fit max-w-full gap-1 overflow-x-auto rounded-xl bg-card p-1 shadow-sm ring-1 ring-foreground/10"><TabsTrigger className="h-9 rounded-lg px-3.5 text-xs font-semibold data-active:bg-primary data-active:text-white data-active:shadow-none dark:data-active:bg-primary">Penjualan</TabsTrigger><TabsTrigger className="h-9 rounded-lg px-3.5 text-xs font-semibold data-active:bg-primary data-active:text-white data-active:shadow-none dark:data-active:bg-primary">Barang Masuk</TabsTrigger><TabsTrigger className="h-9 rounded-lg px-3.5 text-xs font-semibold data-active:bg-primary data-active:text-white data-active:shadow-none dark:data-active:bg-primary">Barang Keluar</TabsTrigger><TabsTrigger className="h-9 rounded-lg px-3.5 text-xs font-semibold data-active:bg-primary data-active:text-white data-active:shadow-none dark:data-active:bg-primary">Stok</TabsTrigger><TabsTrigger className="h-9 rounded-lg px-3.5 text-xs font-semibold data-active:bg-primary data-active:text-white data-active:shadow-none dark:data-active:bg-primary">Servis</TabsTrigger></TabsList>
      <TabsContent value="sales" className="mt-4 flex flex-col gap-4"><section className="grid gap-3 sm:grid-cols-3">{[['Total Penjualan', rupiah(12910000), 'Agustus 2026'], ['Jumlah Transaksi', '86', 'transaksi tercatat'], ['Rata-rata Transaksi', rupiah(150116), 'per transaksi']].map(([label, value, note]) => <div key={label} className="metric-card"><p className="text-sm text-muted-foreground">{label}</p><strong className="mt-1 block text-2xl font-bold tracking-[-.03em]">{value}</strong><p className="mt-1 text-xs text-muted-foreground">{note}</p></div>)}</section><Card className="rounded-[17px]"><CardHeader className="border-b border-border"><CardTitle>Tren Penjualan Mingguan</CardTitle></CardHeader><CardContent className="pt-4"><SalesChart /></CardContent></Card></TabsContent>
      {['in', 'out', 'stock', 'service'].map(v => <TabsContent key={v} value={v} className="mt-4"><Card className="rounded-[17px]"><CardContent className="grid place-items-center py-20 text-center text-sm text-muted-foreground"><span>Pilih rentang tanggal untuk melihat laporan.</span></CardContent></Card></TabsContent>)}
    </Tabs>
  </div>;
}