-- DIAN MOTOR initial schema. Apply to a new Supabase project.
create extension if not exists pgcrypto;
create type public.user_role as enum ('admin','kasir','mekanik');
create type public.stock_type as enum ('IN','OUT');
create type public.service_status as enum ('Menunggu','Dikerjakan','Selesai','Diambil');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null default '', role public.user_role not null default 'kasir', is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, description text, created_at timestamptz not null default now());
create table public.suppliers (id uuid primary key default gen_random_uuid(), name text not null, phone text, address text, email text, created_at timestamptz not null default now());
create table public.customers (id uuid primary key default gen_random_uuid(), name text not null, phone text, address text, created_at timestamptz not null default now());
create table public.products (id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, category_id uuid references public.categories(id) on delete set null, supplier_id uuid references public.suppliers(id) on delete set null, purchase_price numeric(14,2) not null check(purchase_price>=0), selling_price numeric(14,2) not null check(selling_price>=0), stock integer not null default 0 check(stock>=0), minimum_stock integer not null default 0 check(minimum_stock>=0), unit text not null, description text, image_url text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.transactions (id uuid primary key default gen_random_uuid(), transaction_code text not null unique, customer_id uuid references public.customers(id) on delete set null, subtotal numeric(14,2) not null, discount numeric(14,2) not null default 0, total numeric(14,2) not null, payment_method text not null check(payment_method in ('Tunai','Transfer','QRIS')), payment_amount numeric(14,2) not null, change_amount numeric(14,2) not null default 0, status text not null default 'Selesai', idempotency_key uuid not null unique, created_by uuid not null references public.profiles(id), created_at timestamptz not null default now());
create table public.transaction_items (id uuid primary key default gen_random_uuid(), transaction_id uuid not null references public.transactions(id) on delete cascade, product_id uuid not null references public.products(id), quantity integer not null check(quantity>0), price numeric(14,2) not null, subtotal numeric(14,2) not null);
create table public.stock_movements (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id), type public.stock_type not null, quantity integer not null check(quantity>0), reference text, notes text, user_id uuid not null references public.profiles(id), created_at timestamptz not null default now());
create table public.services (id uuid primary key default gen_random_uuid(), service_number text not null unique, customer_id uuid references public.customers(id), vehicle_number text not null, service_type text not null, complaint text, mechanic_id uuid references public.profiles(id), status public.service_status not null default 'Menunggu', total_cost numeric(14,2) not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.service_items (id uuid primary key default gen_random_uuid(), service_id uuid not null references public.services(id) on delete cascade, product_id uuid references public.products(id), description text not null, quantity integer not null default 1 check(quantity>0), price numeric(14,2) not null default 0);
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id) on delete cascade, title text not null, message text not null, link text, read_at timestamptz, created_at timestamptz not null default now());
create table public.business_settings (id boolean primary key default true check(id), business_name text not null default 'DIAN MOTOR', phone text, address text, operating_hours text, updated_at timestamptz not null default now());
create index products_search_idx on public.products using gin(to_tsvector('simple',code||' '||name)); create index transactions_created_idx on public.transactions(created_at desc); create index movements_created_idx on public.stock_movements(created_at desc);

create or replace function public.current_role() returns public.user_role language sql stable security invoker set search_path='' as $$ select role from public.profiles where id=(select auth.uid()) and is_active $$;
alter table public.profiles enable row level security; alter table public.categories enable row level security; alter table public.suppliers enable row level security; alter table public.customers enable row level security; alter table public.products enable row level security; alter table public.transactions enable row level security; alter table public.transaction_items enable row level security; alter table public.stock_movements enable row level security; alter table public.services enable row level security; alter table public.service_items enable row level security; alter table public.notifications enable row level security; alter table public.business_settings enable row level security;
create policy profiles_read on public.profiles for select to authenticated using (id=(select auth.uid()) or public.current_role()='admin');
create policy notifications_own on public.notifications for select to authenticated using (user_id=(select auth.uid()) or user_id is null);
create policy authenticated_read_categories on public.categories for select to authenticated using (public.current_role() is not null);
create policy authenticated_read_suppliers on public.suppliers for select to authenticated using (public.current_role() is not null);
create policy authenticated_read_customers on public.customers for select to authenticated using (public.current_role() is not null);
create policy authenticated_read_products on public.products for select to authenticated using (public.current_role() is not null);
create policy authenticated_read_transactions on public.transactions for select to authenticated using (public.current_role() is not null);
create policy authenticated_read_items on public.transaction_items for select to authenticated using (public.current_role() is not null);
create policy authenticated_read_movements on public.stock_movements for select to authenticated using (public.current_role() is not null);
create policy authenticated_read_services on public.services for select to authenticated using (public.current_role() is not null);
create policy authenticated_read_service_items on public.service_items for select to authenticated using (public.current_role() is not null);
create policy authenticated_read_settings on public.business_settings for select to authenticated using (public.current_role() is not null);
create policy admin_categories on public.categories for all to authenticated using(public.current_role()='admin') with check(public.current_role()='admin'); create policy admin_suppliers on public.suppliers for all to authenticated using(public.current_role()='admin') with check(public.current_role()='admin'); create policy staff_customers on public.customers for all to authenticated using(public.current_role() in ('admin','kasir')) with check(public.current_role() in ('admin','kasir')); create policy admin_products on public.products for all to authenticated using(public.current_role()='admin') with check(public.current_role()='admin'); create policy staff_services on public.services for all to authenticated using(public.current_role() in ('admin','mekanik')) with check(public.current_role() in ('admin','mekanik')); create policy admin_settings on public.business_settings for all to authenticated using(public.current_role()='admin') with check(public.current_role()='admin');

-- Stock mutations are atomic and never allow negative inventory.
create or replace function public.move_stock(p_product uuid,p_type public.stock_type,p_quantity integer,p_reference text default null,p_notes text default null) returns integer language plpgsql security definer set search_path='' as $$ declare v_stock integer; v_role public.user_role; begin select role into v_role from public.profiles where id=auth.uid() and is_active; if v_role is null or p_quantity<=0 then raise exception 'Akses atau jumlah tidak valid'; end if; select stock into v_stock from public.products where id=p_product for update; if p_type='OUT' and v_stock<p_quantity then raise exception 'Stok tidak mencukupi.'; end if; update public.products set stock=stock+(case when p_type='IN' then p_quantity else -p_quantity end),updated_at=now() where id=p_product returning stock into v_stock; insert into public.stock_movements(product_id,type,quantity,reference,notes,user_id) values(p_product,p_type,p_quantity,p_reference,p_notes,auth.uid()); return v_stock; end $$;
revoke all on function public.move_stock(uuid,public.stock_type,integer,text,text) from public; grant execute on function public.move_stock(uuid,public.stock_type,integer,text,text) to authenticated;
